# Generated by Django 2.0.2 on 2018-05-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('stutas', models.IntegerField(choices=[(1, '有效'), (2, '失效')])),
                ('timeflag', models.CharField(max_length=100)),
            ],
        ),
    ]
