# Generated by Django 2.0.2 on 2018-04-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yotools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smscode',
            old_name='phone_number',
            new_name='cellphone',
        ),
    ]
