# Generated by Django 2.0.2 on 2018-05-29 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions_P2',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('overall', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='总权限')),
                ('whole_country', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='全国数据')),
                ('business_online', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='电子商务数据')),
                ('television_shopping', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='电视购物数据')),
                ('B2B_all', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B全部数据')),
                ('B2B_beijing', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B北京数据')),
                ('B2B_huabei', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B华北数据')),
                ('B2B_shuangyashan', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B双鸭山数据')),
                ('B2B_dongbei', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B东北数据')),
                ('B2B_huanan', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B华南数据')),
                ('B2B_xinan', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B西南数据')),
                ('B2B_beifang', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B北方数据')),
                ('B2B_huadong', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B华东数据')),
                ('B2B_xibei', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B西北数据')),
                ('B2B_zhongyuan', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B中原数据')),
                ('direct_store', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='直营店数据')),
                ('hz_agricultural', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='禾中农业数据')),
                ('hz_taste', models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='禾中味道数据')),
            ],
            options={
                'verbose_name': '权限配置_销售额',
                'verbose_name_plural': '权限配置_销售额',
            },
        ),
        migrations.RemoveField(
            model_name='permissions_tdincome',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='permissions_p1',
            options={'verbose_name': '权限配置_今日营收', 'verbose_name_plural': '权限配置_今日营收'},
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_all',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B全部数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_beifang',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B北方数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_beijing',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B北京数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_dongbei',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B东北数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_huabei',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B华北数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_huadong',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B华东数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_huanan',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B华南数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_shuangyashan',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B双鸭山数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_xibei',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B西北数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_xinan',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B西南数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='B2B_zhongyuan',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='B2B中原数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='business_online',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='电子商务数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='direct_store',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='直营店数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='hz_agricultural',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='禾中农业数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='hz_taste',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='禾中味道数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='overall',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='总权限'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='television_shopping',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='电视购物数据'),
        ),
        migrations.AlterField(
            model_name='permissions_p1',
            name='whole_country',
            field=models.IntegerField(choices=[(1, '有查看权限'), (0, '无权限')], default=0, verbose_name='全国数据'),
        ),
        migrations.DeleteModel(
            name='Permissions_tdincome',
        ),
    ]
