# Generated by Django 2.0.7 on 2018-07-06 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_overview',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('today_income', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='今日营收')),
                ('sales_amount', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='销售额')),
                ('store_count', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='新增客户数')),
                ('orderstore_count', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='下单客户数')),
                ('order_count', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='订单数量')),
                ('channal_salesamount_month', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='本月各渠道销售额')),
                ('sales_trend', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='销售趋势')),
                ('classify_amount_month', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='本月商品分类销售额')),
                ('area_salesamount_month', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='本月区域销售额')),
                ('B2B_TOP3_month', models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='本月B2B销售人员TOP3')),
            ],
            options={
                'verbose_name': '总览-显示选择',
                'verbose_name_plural': '总览-显示选择',
            },
        ),
    ]
