# Generated by Django 2.0.2 on 2018-06-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show_overview',
            name='B2B_TOP3_month',
            field=models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='本月B2B销售人员TOP3'),
        ),
        migrations.AddField(
            model_name='show_overview',
            name='area_salesamount_month',
            field=models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='本月区域销售额'),
        ),
        migrations.AddField(
            model_name='show_overview',
            name='channal_salesamount_month',
            field=models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='本月各渠道销售额'),
        ),
        migrations.AddField(
            model_name='show_overview',
            name='classify_amount_month',
            field=models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='本月商品分类销售额'),
        ),
        migrations.AddField(
            model_name='show_overview',
            name='order_count',
            field=models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='订单数量'),
        ),
        migrations.AddField(
            model_name='show_overview',
            name='orderstore_count',
            field=models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='下单客户数'),
        ),
        migrations.AddField(
            model_name='show_overview',
            name='sales_trend',
            field=models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='销售趋势'),
        ),
        migrations.AddField(
            model_name='show_overview',
            name='store_count',
            field=models.IntegerField(choices=[(0, '无查看权限'), (1, '全国数据'), (2, '电商数据'), (3, '电视数据'), (4, 'B2B全部数据'), (5, 'B2B北京数据'), (6, 'B2B华北数据'), (7, 'B2B双鸭山数据'), (8, 'B2B东北数据'), (9, 'B2B华南数据'), (10, 'B2B西南数据'), (11, 'B2B北方数据'), (12, 'B2B华东数据'), (13, 'B2B西北数据'), (14, 'B2B中原数据'), (15, '直营店数据'), (16, '禾中农业数据'), (17, '禾中味道数据')], default=0, verbose_name='新增客户数'),
        ),
    ]
