# Generated by Django 2.0.2 on 2018-05-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions_F1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_income', models.IntegerField(choices=[(1, '全国数据权限'), (2, '大区机构数据权限'), (3, '电商数据权限'), (4, '电视数据权限'), (5, 'B2B数据权限'), (6, '直营店数据权限'), (7, '禾中农业数据权限'), (8, '禾中味道数据权限'), (0, '无查看权限')], default=0, verbose_name='今日营收')),
                ('sales_amount', models.IntegerField(choices=[(1, '有查看权限'), (0, '无查看权限')], default=0, verbose_name='销售额')),
                ('new_customer_count', models.IntegerField(choices=[(1, '有查看权限'), (0, '无查看权限')], default=0, verbose_name='新增客户数')),
                ('ordered_customer_count', models.IntegerField(choices=[(1, '有查看权限'), (0, '无查看权限')], default=0, verbose_name='下单客户数')),
                ('order_amount', models.IntegerField(choices=[(1, '有查看权限'), (0, '无查看权限')], default=0, verbose_name='订单数量')),
                ('channel_total', models.IntegerField(choices=[(1, '有查看权限'), (0, '无查看权限')], default=0, verbose_name='本月各渠道销售额')),
                ('sales_trend', models.IntegerField(choices=[(1, '有查看权限'), (0, '无查看权限')], default=0, verbose_name='道销趋势')),
                ('classify_sale_status', models.IntegerField(choices=[(1, '有查看权限'), (0, '无查看权限')], default=0, verbose_name='本月商品分类销售额')),
                ('regional_sales_amount', models.IntegerField(choices=[(1, '有查看权限'), (0, '无查看权限')], default=0, verbose_name='本月区域销售额')),
                ('B2Bsalesman_TOP3', models.IntegerField(choices=[(1, '有查看权限'), (0, '无查看权限')], default=0, verbose_name='本月B2B销售人员TOP3')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户权限配置表-总览',
                'verbose_name_plural': '用户权限配置表-总览',
            },
        ),
        migrations.CreateModel(
            name='Uprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32, null=True, verbose_name='用户姓名')),
                ('ucellphone', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('uposition', models.IntegerField(choices=[(1, '前端登录 总经理'), (2, '前端登录 副总经理'), (3, '前端登录 大区经理'), (4, '前端登录 产品部经理'), (5, '前端登录 北京招商部经理'), (6, '前端登录 北京招商部主管'), (7, '前端登录 北京招商部专员'), (8, '前端登录 直营事业部经理'), (9, '前端登录 电视直销部经理'), (10, '前端登录 电子商务部经理'), (11, '前端登录 数据分析人员'), (12, '前端登录 其他人员'), (100, '后台登录 上帝权限'), (101, '后台登录 后台管理')], default=12, help_text='权限设定', verbose_name='用户角色')),
                ('ustatus', models.IntegerField(choices=[(1, '已审核'), (0, '待审核'), (-1, '审核未通过'), (-2, '已删除')], default=0, verbose_name='用户状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息拓展表',
                'verbose_name_plural': '用户信息拓展表',
            },
        ),
    ]
