# Generated by Django 2.0.2 on 2018-05-23 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions_f1',
            options={'verbose_name': '用户权限配置表', 'verbose_name_plural': '用户权限配置表'},
        ),
        migrations.RemoveField(
            model_name='permissions_f1',
            name='id',
        ),
        migrations.AlterField(
            model_name='permissions_f1',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
