# Generated by Django 2.0.2 on 2018-05-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0002_auto_20180523_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions_f1',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permissions_F1',
        ),
    ]
