# Generated by Django 2.0.7 on 2018-07-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sale_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateField()),
                ('salesname', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('imageurl', models.CharField(max_length=256)),
                ('checkif', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sale_upload',
            },
        ),
    ]
