# Generated by Django 2.0.2 on 2018-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='b2b_goodstable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(verbose_name='创建日期')),
                ('organName', models.CharField(max_length=64, verbose_name='机构名称')),
                ('orderStore', models.CharField(max_length=16, verbose_name='订单店铺')),
                ('orderStoreName', models.CharField(max_length=64, verbose_name='订单归属门店名称')),
                ('orderNo', models.CharField(max_length=32, verbose_name='单据编号')),
                ('tbNo', models.CharField(max_length=32)),
                ('secondIcatName', models.CharField(max_length=64)),
                ('skuCode', models.CharField(max_length=16)),
                ('skuName', models.CharField(max_length=100)),
                ('skuNum', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='skuNum')),
                ('realSkuNum', models.DecimalField(decimal_places=5, max_digits=22, verbose_name='realSkuNum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='数量')),
                ('memberPin', models.CharField(max_length=64, verbose_name='会员用户名')),
                ('regionName', models.CharField(default='', max_length=254, verbose_name='地区名称')),
                ('realName', models.CharField(max_length=32, verbose_name='用户姓名')),
                ('supName', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'b2b_goodstable',
            },
        ),
        migrations.CreateModel(
            name='b2b_ordertable',
            fields=[
                ('createDate', models.DateField(verbose_name='创建日期')),
                ('organName', models.CharField(max_length=64, verbose_name='机构名称')),
                ('orderStore', models.CharField(max_length=16, verbose_name='订单店铺')),
                ('orderStoreName', models.CharField(max_length=64, verbose_name='订单归属门店名称')),
                ('orderNo', models.CharField(max_length=32, verbose_name='单据编号')),
                ('tbNo1', models.CharField(max_length=32, verbose_name='tbNo1')),
                ('tbNo2', models.CharField(max_length=32, verbose_name='tbNo2')),
                ('realPayAmount', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='客户实际支付的金额')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=22, verbose_name='数量')),
                ('memberPin', models.CharField(max_length=64, verbose_name='会员用户名')),
                ('regionName', models.CharField(default='', max_length=254, verbose_name='地区名称')),
                ('realName', models.CharField(max_length=32, verbose_name='用户姓名')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'b2b_ordertable',
            },
        ),
        migrations.CreateModel(
            name='b2b_posgoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(verbose_name='创建日期')),
                ('orderStore', models.IntegerField(verbose_name='订单店铺')),
                ('orderStoreName', models.CharField(max_length=40, verbose_name='订单归属门店名称')),
                ('organCode', models.IntegerField()),
                ('organName', models.CharField(max_length=40)),
                ('orderNo', models.CharField(max_length=40)),
                ('secondIcatName', models.CharField(max_length=40)),
                ('skuCode', models.CharField(max_length=40)),
                ('skuName', models.CharField(max_length=40)),
                ('skuNum', models.DecimalField(decimal_places=5, max_digits=22)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=22, verbose_name='数量')),
                ('realPayAmount', models.DecimalField(decimal_places=5, max_digits=22)),
            ],
            options={
                'db_table': 'b2b_posgoods',
            },
        ),
        migrations.CreateModel(
            name='b2b_storeb2b',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ownerno', models.CharField(max_length=32)),
                ('ownerPin', models.CharField(max_length=64)),
                ('ownerName', models.CharField(max_length=32)),
                ('cellphone', models.CharField(max_length=16)),
                ('shopName', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('status', models.IntegerField()),
                ('areaCode', models.CharField(max_length=32)),
                ('areaName', models.CharField(max_length=64)),
                ('levelCode', models.CharField(max_length=32)),
                ('levelName', models.CharField(max_length=64)),
                ('recomm_username', models.CharField(max_length=64)),
                ('sales_username', models.CharField(max_length=32)),
                ('sales_cell', models.CharField(max_length=16)),
                ('create_dt', models.DateField()),
            ],
            options={
                'db_table': 'b2b_storeb2b',
            },
        ),
    ]
