# Generated by Django 2.0.2 on 2018-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzyg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2b_goodstable',
            name='saleUnit',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2b_posgoods',
            name='saleUnit',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
