# Generated by Django 2.0.7 on 2018-07-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hzyg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2b_posgoods',
            old_name='realSaleStockUnit',
            new_name='saleStockNum',
        ),
    ]
