# Generated by Django 2.0.2 on 2018-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzyg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2b_goodstable',
            name='orderStatus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='b2b_goodstable',
            name='payMode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='b2b_ordertable',
            name='orderStatus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='b2b_ordertable',
            name='payMode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='b2b_ordertable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='b2b_storeb2b',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
