# Generated by Django 2.0.2 on 2018-06-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hzyg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2b_goodstable',
            old_name='secondlcatName',
            new_name='secondIcatName',
        ),
        migrations.RenameField(
            model_name='b2b_posgoods',
            old_name='secondlcatName',
            new_name='secondIcatName',
        ),
    ]
